# Generated by Django 3.0.8 on 2021-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='consent',
            field=models.CharField(choices=[('------', '------'), ('Y', 'Yes'), ('N', 'No')], default='------', max_length=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('------', '------'), ('M', 'Male'), ('F', 'Female')], default='------', max_length=6),
        ),
    ]
