# Generated by Django 3.0.8 on 2021-01-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210122_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='consent',
            new_name='Consent',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='dob',
            new_name='DateOfBirth',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='school',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='startDate',
            new_name='StartDate',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='surname',
            new_name='Surname',
        ),
    ]
